package com.hayukleung.mpermissions

/**
 * MPermissions Request Codes
 *
 * 何时需要动态申请权限？
 *
 * 1. 危险权限
 * 2. Android 版本 >= 6.0
 * 3. targetSdkVersion >= 23
 */

val PERMISSION_REQUEST_CODE_CALENDAR = 0x0001
val PERMISSION_REQUEST_CODE_CAMERA = 0x0002
val PERMISSION_REQUEST_CODE_CONTACTS = 0x0003
val PERMISSION_REQUEST_CODE_LOCATION = 0x0004
val PERMISSION_REQUEST_CODE_MICROPHONE = 0x0005
val PERMISSION_REQUEST_CODE_PHONE = 0x0006
val PERMISSION_REQUEST_CODE_SENSORS = 0x0007
val PERMISSION_REQUEST_CODE_SMS = 0x0008
val PERMISSION_REQUEST_CODE_STORAGE = 0x0009

val REQUEST_CODE_SETTING = 0x000A