package com.hayukleung.mpermissions

/**
 * MPermissions Request Codes
 *
 * 何时需要动态申请权限？
 *
 * 1. 危险权限
 * 2. Android 版本 >= 6.0
 * 3. targetSdkVersion >= 23
 */

// calendar
val PERMISSION_REQUEST_CODE_READ_CALENDAR = 0x0011
val PERMISSION_REQUEST_CODE_WRITE_CALENDAR = 0x0012

// camera
val PERMISSION_REQUEST_CODE_CAMERA = 0x0002

// contacts
val PERMISSION_REQUEST_CODE_GET_ACCOUNTS = 0x0031
val PERMISSION_REQUEST_CODE_READ_CONTACTS = 0x0032
val PERMISSION_REQUEST_CODE_WRITE_CONTACTS = 0x0033

// location
val PERMISSION_REQUEST_CODE_ACCESS_COARSE_LOCATION = 0x0041
val PERMISSION_REQUEST_CODE_ACCESS_FINE_LOCATION = 0x0042

// microphone
val PERMISSION_REQUEST_CODE_MICROPHONE = 0x0005

// phone
val PERMISSION_REQUEST_CODE_ADD_VOICEMAIL = 0x0061
val PERMISSION_REQUEST_CODE_CALL_PHONE = 0x0062
val PERMISSION_REQUEST_CODE_PROCESS_OUTGOING_CALLS = 0x0063
val PERMISSION_REQUEST_CODE_READ_PHONE_STATE = 0x0064
val PERMISSION_REQUEST_CODE_READ_CALL_LOG = 0x0065
val PERMISSION_REQUEST_CODE_USE_SIP = 0x0066
val PERMISSION_REQUEST_CODE_WRITE_CALL_LOG = 0x0067

// sensors
val PERMISSION_REQUEST_CODE_SENSORS = 0x0007

// sms
val PERMISSION_REQUEST_CODE_SEND_SMS = 0x0081
val PERMISSION_REQUEST_CODE_RECEIVE_SMS = 0x0082
val PERMISSION_REQUEST_CODE_READ_SMS = 0x0083
val PERMISSION_REQUEST_CODE_RECEIVE_WAP_PUSH = 0x0084
val PERMISSION_REQUEST_CODE_RECEIVE_MMS = 0x0085

// storage
val PERMISSION_REQUEST_CODE_WRITE_EXTERNAL_STORAGE = 0x0091
val PERMISSION_REQUEST_CODE_READ_EXTERNAL_STORAGE = 0x0092

// setting
val REQUEST_CODE_SETTING = 0x000A

// install
val PERMISSION_REQUEST_CODE_REQUEST_INSTALL_PACKAGE = 0x00B0